version: '3'
services:
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack:6.2.6-v2
    restart: always
    ports:
      - "7070:8001"
      - "6379:6379"
    expose:
      - "7070"
      - "6379"